apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-docker
  name: frontend-headless 
spec:
  clusterIP: None 
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    name: spring-docker 
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}